### ISSUE TITLE
The "variant" data type is not supported.

### ISSUE THREAD

**Issue by JamoCA** [sebtools/com.sebtools#3]
After reading an article regarding memory leaks w/the native Adobe DataDirect SQL driver, I decided to test the Microsoft JDBCSQL connector.  I've found that in addition to less memory problems, it's also a little faster.  There's only one issue though; JDBC doesn't know how to handle "variant" data types and throws an error.

This means that unknown variant values will need to be cast (or converted) to VARCHAR in order to work.

I'm using the SpamFilter component and was receiving a 500 error when using the JDBC connector.

Line 23 of DataMgr_MSSQL.cfc, the `getDatabaseVersion` function uses the following SQL:
`SELECT SERVERPROPERTY('productversion') AS VersionNum`
and should be updated to:
`SELECT CAST(SERVERPROPERTY('productversion') AS VARCHAR(255)) AS VersionNum`

**Comment by sebtools** [comment]
Sorry I just saw this. I added this to DataMgr now. Thanks!
