### ISSUE TITLE
Missing custom tags

### ISSUE THREAD

**Issue by JamoCA** [sebtools/com.sebtools#7]
I upgraded to this version available at Github and multiple CFCs appear to require custom tags that don't exist in this project:

- DMPara.cfm
- DMQuery.cfm
- DMSQL.cfm
- DMUdfs.cfm

I found a blog entry that referenced these files, but the link was to the riaForge website which isn't around anymore.

**Comment by sebtools** [comment]
The missing tags have been added now. Thanks for the report!
