### ISSUE TITLE
SpamFilters Penalizes use of reCaptcha & hCaptcha

### ISSUE THREAD

**Issue by JamoCA** [sebtools/com.sebtools#8]
When I added [reCaptcha](https://www.google.com/recaptcha/about/) and then migrated to [hCaptcha](https://www.hcaptcha.com/), I saw that SpamFilter was penalizing the submission due to the `grecaptcharesponse`, `g-recaptcha-response` and `h-captcha-response` values in the FORM scope. Some legitimate email addresses that contained digits were also being awarded points and triggering spam detection.

I recommend adding an ignore list as well as a function to identify which rules are being used and the associated points that go with the rule.  _(I submitted a patch to assist with this.)_

**Comment by sebtools** [comment]
Good idea. Merged. Thanks!
